language: python
python:
    - 3.6
    - 3.9

install:
    - travis_retry pip install -r requirements.txt

script:
    - python manage.py test

#branches:
#    only:
#        - master

